Add ratings typings
CM20314-Group-2/futureproof pull request #14
Opened 2022-03-11 00:12 UTC by Matthew5002

Fixed a number of dependencies + references + recovered missing file
Added typings for business FutureProof rating breakdown + certificates
Added documentation for ratings folder views.
Made certificates and ratings breakdown modular (input array of certificates/ratings)

2022-03-14 23:09 UTC, bridges-wood requested changes
Excellent work. Couple of tiny things, and if you bring your branch up to date with @choobs1 's PR, then we'll be good to go.

2022-03-14 23:09 UTC, bridges-wood commented on packages/client/src/components/ratings/FutureProofRatingView.tsx
> + * This function creates the whole FutureProof rating view, including certificates and individual ratings breakdown.
This could be more descriptive

2022-03-14 23:09 UTC, bridges-wood requested changes
Excellent work. Couple of tiny things, and if you bring your branch up to date with @choobs1 's PR, then we'll be good to go.

2022-03-14 23:10 UTC, bridges-wood requested changes
Excellent work. Couple of tiny things, and if you bring your branch up to date with @choobs1 's PR, then we'll be good to go.

2022-03-19 20:07 UTC, Matthew5002 commented on packages/client/src/components/BusinessViews/ImagesCarousel.spec.tsx
> +  const { toJSON } = render(<ImagesCarousel Image1={Image1} Image2={Image2} Image3={Image3} Image4={Image4}/>)
That was something Cam was working on so I don't want to mess around with it and have even more merge issues. (Agreed though haha)

2022-03-20 13:07 UTC, bridges-wood approved these changes
LGTM

2022-03-25 21:28 UTC, choobs1 reviewed
LETS GO NO MORE BABEL PROBLEMS?!! 🙌

2022-03-26 00:28 UTC, merged